### ISSUE TITLE
Colors in (nested) dictionaries fail to appear

### ISSUE THREAD

**Issue by metakirby5** [97-109-107/whizkers-server#5]
If colors are stored in a dictionary, the entire dictionary is used as a "color," and doesn't display properly. To solve this, you would likely need a recursive dictionary parser. Below is one example on which the behavior is demonstrated.

``` yaml
wallpapers: "/usr/share/backgrounds/in_rotation/monochrome_sakura.jpg"

colors:
  name:         "6c37"
  primary:      "blue"
  secondary:    "red"
  background:   "#202025"
  foreground:   "#b8b8c8"
  black:
    normal:     "#353540"
    bold:       "#545466"
  red:
    normal:     "#8c5760"
    bold:       "#b26f7a"
  green:
    normal:     "#7b8c58"
    bold:       "#9db270"
  yellow:
    normal:     "#8c6e43"
    bold:       "#b28c55"
  blue:
    normal:     "#58698c"
    bold:       "#7086b2"
  magenta:
    normal:     "#7b5e7d"
    bold:       "#9c77b2"
  cyan:
    normal:     "#66808c"
    bold:       "#82a2b2"
```
